# Generated by Django 3.2.12 on 2022-04-10 19:37

import core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dokument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kuerzel', models.CharField(max_length=5)),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(null=True, upload_to=core.models.dokument_file_path)),
                ('lastUpdate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fahrzeug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kuerzel', models.CharField(max_length=5)),
                ('name', models.CharField(max_length=255)),
                ('fahrzeug', models.BooleanField(default=False)),
                ('anhaenger', models.BooleanField(default=False)),
                ('type', models.CharField(blank=True, max_length=255)),
                ('lenkerberechtigung', models.CharField(blank=True, max_length=1)),
                ('stationierung', models.CharField(blank=True, max_length=255)),
                ('personenkapazitaet', models.IntegerField(null=True)),
                ('treibstoff', models.CharField(blank=True, max_length=50)),
                ('nutzlast', models.IntegerField(null=True)),
                ('ladebordwand', models.BooleanField(default=False)),
                ('ladekran', models.BooleanField(default=False)),
                ('wassertank', models.CharField(blank=True, max_length=255)),
                ('wassertankAbnehmbar', models.BooleanField(default=False)),
                ('geschlossenerAufbau', models.BooleanField(default=False)),
                ('wechselaufbau', models.TextField(blank=True)),
                ('anhaengervorrichtung', models.CharField(blank=True, max_length=255)),
                ('lastUpdate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gefahr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kuerzel', models.CharField(max_length=5)),
                ('name', models.CharField(max_length=255)),
                ('beschreibung', models.TextField(blank=True)),
                ('ausloeser', models.CharField(blank=True, max_length=255)),
                ('feld1Name', models.CharField(blank=True, max_length=255)),
                ('feld1Value', models.CharField(blank=True, max_length=255)),
                ('feld2Name', models.CharField(blank=True, max_length=255)),
                ('feld2Value', models.CharField(blank=True, max_length=255)),
                ('feld3Name', models.CharField(blank=True, max_length=255)),
                ('feld3Value', models.CharField(blank=True, max_length=255)),
                ('feld4Name', models.CharField(blank=True, max_length=255)),
                ('feld4Value', models.CharField(blank=True, max_length=255)),
                ('feld5Name', models.CharField(blank=True, max_length=255)),
                ('feld5Value', models.CharField(blank=True, max_length=255)),
                ('folgen', models.CharField(blank=True, max_length=255)),
                ('gefahren', models.CharField(blank=True, max_length=255)),
                ('rollen', models.JSONField(default=list, null=True)),
                ('massnahmen', models.JSONField(default=list, null=True)),
                ('dokumente', models.JSONField(default=list, null=True)),
                ('lastUpdate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Katastrophe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kuerzel', models.CharField(max_length=5)),
                ('name', models.CharField(max_length=255)),
                ('beschreibung', models.TextField(blank=True)),
                ('rollen', models.JSONField(default=list, null=True)),
                ('massnahmen', models.JSONField(default=list, null=True)),
                ('gefahren', models.JSONField(default=list, null=True)),
                ('lastUpdate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='KMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artikel', models.CharField(max_length=255)),
                ('bemerkung', models.CharField(blank=True, max_length=255)),
                ('menge', models.IntegerField(null=True)),
                ('stationierungsort', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Kontakt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kuerzel', models.CharField(max_length=5)),
                ('name', models.CharField(max_length=255)),
                ('funktion', models.CharField(blank=True, max_length=255)),
                ('telefon', models.CharField(blank=True, max_length=255)),
                ('telefon2', models.CharField(blank=True, max_length=255)),
                ('telefon3', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(blank=True, max_length=255)),
                ('lastUpdate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Massnahme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kuerzel', models.CharField(max_length=5)),
                ('name', models.CharField(max_length=255)),
                ('beschreibung', models.TextField(blank=True)),
                ('kategorie', models.CharField(blank=True, max_length=255)),
                ('verantwortung', models.CharField(blank=True, max_length=255)),
                ('verstaendigung', models.JSONField(default=list, null=True)),
                ('staerke', models.IntegerField(null=True)),
                ('fahrzeuge', models.JSONField(default=list, null=True)),
                ('feld1Name', models.CharField(blank=True, max_length=255)),
                ('feld1Value', models.CharField(blank=True, max_length=255)),
                ('feld2Name', models.CharField(blank=True, max_length=255)),
                ('feld2Value', models.CharField(blank=True, max_length=255)),
                ('feld3Name', models.CharField(blank=True, max_length=255)),
                ('feld3Value', models.CharField(blank=True, max_length=255)),
                ('feld4Name', models.CharField(blank=True, max_length=255)),
                ('feld4Value', models.CharField(blank=True, max_length=255)),
                ('feld5Name', models.CharField(blank=True, max_length=255)),
                ('feld5Value', models.CharField(blank=True, max_length=255)),
                ('durchfuehrung', models.TextField(blank=True)),
                ('rueckbau', models.TextField(blank=True)),
                ('lastUpdate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Modul',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bezeichnung', models.CharField(max_length=255)),
                ('kuerzel', models.CharField(max_length=5)),
                ('icon', models.CharField(max_length=50)),
                ('reihenfolge', models.IntegerField(null=True)),
                ('permissions', models.JSONField(default=list, null=True)),
                ('lastUpdate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rolle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kuerzel', models.CharField(max_length=5)),
                ('name', models.CharField(max_length=255)),
                ('beschreibung', models.TextField(blank=True)),
                ('erreichbarkeit', models.JSONField(default=list, null=True)),
                ('notruf', models.CharField(blank=True, max_length=255)),
                ('aufgaben', models.TextField(blank=True)),
                ('verstaendigung', models.JSONField(default=list, null=True)),
                ('lastUpdate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FahrzeugFoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(null=True, upload_to=core.models.fahrzeug_image_file_path)),
                ('lastUpdate', models.DateTimeField(auto_now_add=True)),
                ('fahrzeug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.fahrzeug')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
