# Generated by Django 3.2.13 on 2022-04-30 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_is_verwaltung'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_benutzerverwaltung',
            field=models.BooleanField(default=False),
        ),
    ]
