# Generated by Django 3.2.16 on 2023-01-29 20:14

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_is_benutzerverwaltung'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fahrzeugfoto',
            name='file',
            field=models.FileField(max_length=255, null=True, upload_to=core.models.fahrzeug_image_file_path),
        ),
    ]
